### ISSUE TITLE
NPE when accessing People page

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#2070]
**Steps to reproduce**

1. Go to People page
2. See logs

**Current behaviour**

NPE is logged

```
java.lang.NullPointerException: Cannot invoke "org.exoplatform.commons.api.settings.SettingValue.getValue()" because "userCardFirstFieldSetting" is null
	at org.exoplatform.social.rest.impl.user.UserRestResourcesV1.getUserCardSettings(UserRestResourcesV1.java:1559)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.exoplatform.services.rest.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:185)
	at org.exoplatform.services.rest.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:178)
	at org.exoplatform.services.rest.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:657)
	at org.exoplatform.services.rest.impl.RequestDispatcher.dispatch(RequestDispatcher.java:602)
	at org.exoplatform.services.rest.impl.RequestDispatcher.dispatch(RequestDispatcher.java:507)
	at org.exoplatform.services.rest.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:141)
	at org.exoplatform.services.rest.servlet.RestServlet.onService(RestServlet.java:100)
```

**Expected behavior**

A clean log

**Comment by boubaker** [comment]
@rdenarie I reproduce this on builders and locally. Can you check this please

**Comment by rdenarie** [comment]
@ahamdi Can you take this point ?

Thanks

**Comment by ahamdi** [comment]
@rdenarie Yes I will handle this issue
