### ISSUE TITLE
[tasks][bug]plan view is ko in langage different of EN & FR

### ISSUE THREAD

**Issue by hthabti** [Meeds-io/meeds#2140]
7.0.x
6.5.x

steps:
set plf langage to langage except english or french
open tasks project
create tasks with start and end date
open plan view

actual:
nothing displayed in plan view and error in browser console

vueGRP--min.js:26 TypeError: Cannot read properties of undefined (reading '4')
    at Object.format (ganttChart--min.js:6:1536)
    at p.get_date_info (ganttChart--min.js:6:22606)
    at ganttChart--min.js:6:22493
    at Array.map ()
    at p.get_dates_to_draw (ganttChart--min.js:6:22468)
    at p.make_dates (ganttChart--min.js:6:22117)
    at p.render (ganttChart--min.js:6:18711)
    at p.change_view_mode (ganttChart--min.js:6:16988)
    at new p (ganttChart--min.js:6:14276)
    at a.initGanttChart (task-management:TasksManagement--min.js:6:156334)
Ue @ vueGRP--min.js:26

expected:
plan view should be available as it is the case for french & english

feedback:
72317

**Comment by srenault-meeds** [comment]
Hi @hthabti ,

What is the status, please?
