### ISSUE TITLE
Server unable to start if we remove meeds-wallet addon

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/meeds#383]
**Steps to reproduce**

1. Remove meeds-wallet addon : ./addon uninstall meeds-wallet
2. Start the server
3. Try to login 

**Current behaviour**
The server display a white page with error in log : 

> 2022-11-07 19:57:30,572 | WARN  | An error occured while cache user profile [o.exoplatform.web.CacheUserProfileFilter<http-nio-0.0.0.0-8080-exec-8>] 
> javax.servlet.ServletException: Filter execution threw an exception
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:196)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.exoplatform.web.CacheUserProfileFilter.doFilter(CacheUserProfileFilter.java:73)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.exoplatform.web.login.ConversationStateUpdateFilter.doFilter(ConversationStateUpdateFilter.java:66)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.exoplatform.services.security.web.SetCurrentIdentityFilter.doFilter(SetCurrentIdentityFilter.java:88)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.exoplatform.web.login.RememberMeFilter.doFilter(RememberMeFilter.java:135)
> 	at org.exoplatform.web.login.RememberMeFilter.doFilter(RememberMeFilter.java:52)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.gatein.security.oauth.webapi.OAuthDelegateFilter.doFilter(OAuthDelegateFilter.java:58)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.gatein.sso.integration.SSODelegateFilter.doFilter(SSODelegateFilter.java:61)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.exoplatform.container.web.PortalContainerFilter.doFilter(PortalContainerFilter.java:78)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.gatein.portal.init.PortalCheckInitFilter.doFilter(PortalCheckInitFilter.java:66)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.exoplatform.frameworks.jcr.web.ThreadLocalSessionProviderInitializedFilter.doFilter(ThreadLocalSessionProviderInitializedFilter.java:122)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
> 	at org.gatein.sso.integration.SSODelegateValve.invoke(SSODelegateValve.java:142)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.gatein.sso.agent.tomcat.ServletAccessValve.invoke(ServletAccessValve.java:55)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
> 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:312)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: java.util.ServiceConfigurationError: io.jsonwebtoken.io.Serializer: io.jsonwebtoken.jackson.io.JacksonSerializer Unable to get public no-arg constructor
> 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
> 	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:673)
> 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1233)
> 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
> 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
> 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
> 	at io.jsonwebtoken.impl.lang.Services.loadFirst(Services.java:110)
> 	at io.jsonwebtoken.impl.lang.Services.loadFirst(Services.java:100)
> 	at io.jsonwebtoken.impl.lang.LegacyServices.loadFirst(LegacyServices.java:24)
> 	at io.jsonwebtoken.impl.DefaultJwtBuilder.compact(DefaultJwtBuilder.java:291)
> 	at org.exoplatform.webconferencing.server.filter.SessionFilter.doFilter(SessionFilter.java:49)
> 	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:106)
> 	at org.exoplatform.services.filters.sessionProvider.ThreadLocalACLSessionProviderInitializedFilter.doFilter(ThreadLocalACLSessionProviderInitializedFilter.java:45)
> 	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:106)
> 	at org.exoplatform.oauth.filter.OAuthAbstractFilter.doFilter(OAuthAbstractFilter.java:61)
> 	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:106)
> 	at org.exoplatform.push.filter.AuthenticationHeaderFilter.doFilter(AuthenticationHeaderFilter.java:69)
> 	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:106)
> 	at org.exoplatform.web.filter.ExtensibleFilter.doFilter(ExtensibleFilter.java:79)
> 	at org.exoplatform.web.filter.GenericFilter.doFilter(GenericFilter.java:70)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	... 50 common frames omitted
> Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
> 	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
> 	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
> 	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
> 	at java.base/java.lang.Class.getConstructor(Class.java:2151)
> 	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:660)
> 	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:657)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:668)
> 	... 69 common frames omitted
> Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
> 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	... 77 common frames omitted
> 

**Expected behavior**

No error at login

**Comment by srenault-meeds** [comment]
Hi, can you please tell us if the status is doing or is it done?
Thanks
@rdenarie

**Comment by rdenarie** [comment]
In progress.
I have to backport the fix on develop. 
Thanks for the reminder

**Comment by rdenarie** [comment]
Commit backported

**Comment by rdenarie** [comment]
I reopen this task as there is a regression on meeds startup after this commit

**Comment by srenault-meeds** [comment]
Is that still a problem?
Indeed, we have reviewed this I think during the MIP#154 implementation

**Comment by Jihed525** [comment]
I do not reproduce oin latest server
