### ISSUE TITLE
Error when indexing users after Merge of Meeds-io/MIPs#38

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/meeds#679]
**Steps to reproduce**

1. Login with a user
2. See error in log

```
2023-02-14 18:49:36,382 | WARN  | Error while *updating* index entry of entity, type = profile, id =1, cause: [o.e.c.s.i.i.ElasticIndexingOperationProcessor<ExoScheduler_Worker-3>] 
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "multiValues" is null
	at org.exoplatform.social.core.jpa.search.ProfileIndexingServiceConnector.getDocument(ProfileIndexingServiceConnector.java:254)
	at org.exoplatform.social.core.jpa.search.ProfileIndexingServiceConnector.update(ProfileIndexingServiceConnector.java:76)
	at org.exoplatform.commons.search.es.client.ElasticContentRequestBuilder.getUpdateDocumentRequestContent(ElasticContentRequestBuilder.java:201)
	at org.exoplatform.commons.search.index.impl.ElasticIndexingOperationProcessor.processCUD(ElasticIndexingOperationProcessor.java:398)
	at org.exoplatform.commons.search.index.impl.ElasticIndexingOperationProcessor.processBulk(ElasticIndexingOperationProcessor.java:203)
	at org.exoplatform.commons.search.index.impl.ElasticIndexingOperationProcessor.process(ElasticIndexingOperationProcessor.java:152)
	at org.exoplatform.commons.search.job.BulkIndexingJob.execute(BulkIndexingJob.java:41)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

```

**Current behaviour**

Error prevent indexing new and existing users

**Expected behavior**

No errors when indexing users

**Comment by srenault-meeds** [comment]
FYI @margondicco @mzorai regarding MIP38
