### ISSUE TITLE
Manage notifications page and notification administration pages are blank after upgrade from 1.4.x to 1.5.x

### ISSUE THREAD

**Issue by azayati** [Meeds-io/meeds#850]
**Steps to reproduce**

1. Start a meeds 1.4.x instance
2. Connect with root
3. Go to administration -> Notifications, and deactivate all notifications channels for "Post on my Stream"
4. Create a new user
5. Log with this user
6. Make migration to 1.5.x
7. Log with user
8. Go to settings page
9. Try to open "manage notifications"
10. Log with root
11.  Try to open notifications administration page

**(optional) Affected version**

Meeds 1.5.x upgraded from Meeds 1.4.x

**Current behavior**

- When loading settings page, the rest request http://localhost:8080/portal/rest/notifications/settings/john is in error
- There is a trace in the log 
```
2023-03-02 17:47:29,820 | ERROR | Computing of resource romain threw an exception [exo.kernel.component.cache.FutureCache<http-nio-0.0.0.0-8080-exec-1>] 
java.lang.UnsupportedOperationException: null
    at java.base/java.util.AbstractList.add(AbstractList.java:153)
    at java.base/java.util.AbstractList.add(AbstractList.java:111)
    at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:336)
    at org.exoplatform.settings.jpa.JPAPluginSettingServiceImpl.getPluginChannels(JPAPluginSettingServiceImpl.java:206)
    at org.exoplatform.settings.jpa.JPAUserSettingServiceImpl.getDefaultSettings(JPAUserSettingServiceImpl.java:232)
    at org.exoplatform.settings.jpa.JPAUserSettingServiceImpl.get(JPAUserSettingServiceImpl.java:131)
    at org.exoplatform.settings.jpa.CacheUserSettingServiceImpl$1.retrieve(CacheUserSettingServiceImpl.java:51)

```
- When clicking on "Manage notification", the page is empty.
- Notification administration page is in error and empty also

**Expected behavior**

- Settings page is loaded correctly
-  Notification administration page  is loaded correctly

**Comment by srenault-meeds** [comment]
Is that still a problem ?

**Comment by srenault-meeds** [comment]
is it done?

**Comment by srenault-meeds** [comment]
What is the status please? @Jihed525
