### ISSUE TITLE
Push notifications are not sent because of missing title

### ISSUE THREAD

**Issue by ahamdi** [Meeds-io/meeds#904]
**Steps to reproduce**

1. Do an action that sends a push notification to another user
2. Check Mobile notification
3. An exception is thrown and the notif is not sent : 
```
2023-04-13 01:17:42,672 | ERROR | Cannot send push notification to user patrice_lamarque [org.exoplatform.push.channel.PushChannel<Notification-Thread>] java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "org.exoplatform.push.domain.Message.getTitle()" is null 
at org.exoplatform.push.service.fcm.FCMMessagePublisher.send(FCMMessagePublisher.java:157) 
at org.exoplatform.push.channel.PushChannel.lambda$dispatch$0(PushChannel.java:99) 
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) 
at org.exoplatform.push.channel.PushChannel.dispatch(PushChannel.java:88) 
at org.exoplatform.commons.api.notification.lifecycle.DefaultLifecycle.process(DefaultLifecycle.java:35) 
at org.exoplatform.commons.api.notification.lifecycle.DefaultLifecycle.process(DefaultLifecycle.java:51) 
at org.exoplatform.commons.notification.impl.service.NotificationServiceImpl.process(NotificationServiceImpl.java:150)
........
 ```

**Comment by srenault-meeds** [comment]
Meeds Related? (wondering because no mobile app)
